travis:
  secure:
    BINSTAR_TOKEN: WXTSJtpFGBUEtAj+RtkWPep4ho22nVEy2PLJFfHgeMdLa1QiCnk6QUCGonLI8tMqXOTh9FuhxePmlt4TAArus4vephhE0UeTy8KHzUrJkYTcumG4oci5N+shlSkROZ3waKb0vfTJNHrN5v+oLdTNoIUkid0IF1mfOLNJVnREkdRcg3CXljhrVDmpg3UnmGOxYd/xz6x/cvkqv360F69HbHJRgX1pT5mbIG41b0n5zMiCpBipzWwNUk4lJ6QNtdDjUw/Fhwtfhc/iVP3GqY7p6jENElVtaJMoKSf040BNnRw2P64l/ogkJ+jCPjwVxHZ3dgVnbSF9XZHrTvmnylgH4nAhI3Amv/NIzk3Rkk7Td9kh0901iLoDxVs8IwzmGjzYYMBpFWjSSXnSg0ivrAe1oyNOCshleUu27xhUxD1SA/Rhf6pzAZOrPdLjUq/6lem2nj1ZGutQf0zr5pDoZGgLSuuyT35p67FBFjedvEFi8AjzWahBczT+sMtSjbMrW16mvraPBwCAVOnCYfgVJTt0DnGbnlvIWU5tqb86J0uDB+t2Gu1kPQjC1+rtHQQgJrPjQL1LfvlJR5AxexrEm9YQIYlH3vc6oklRfFQm5pROtgse5F6p2hbByhlIpvijnSVlnM9Z+LeQ5KHNk6m3FnqFOvUrzDMpeYe0R9dV/mO/5HM=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
